### ISSUE TITLE
No license,can I use it directly?

### ISSUE THREAD

**Issue by leepeozzz** [siebeprojects/samples-keyboardheight#10]

**Comment by siebeprojects** [comment]
Yes you can use all the code change it, modify it.
Thanks for noticing it, I will add a bit later i.e. the MIT license to it.

**Comment by crykn** [comment]
Hey @siebeprojects, sorry to dig up this old issue. Have you decided on a license for the project yet?

**Comment by siebeprojects** [comment]
@crykn it seems I forgot to still add a license :-) 
But please use the code as you please, it is entirely free and you can do whatever you want with it.
